require('user.plugins')

require('user.basic-plugins')
require('user.cmp')
require('user.colorscheme')
require('user.keybinds')
require('user.options')
require("user.lsp")
require('user.lualine')
require('user.nvim-treesitter')
require('user.telescope-nvim')
require('user.gutentags')
