vim.opt.completeopt = { "menuone", "noselect" }
vim.opt.hlsearch = false
vim.opt.ignorecase = true
vim.opt.showmode = false
vim.opt.splitright = true
vim.opt.wrap = false
vim.opt.number = true
vim.opt.expandtab = true
vim.opt.showmode = false
vim.opt.undofile = true
vim.opt.shiftwidth = 4
vim.o.updatetime = 300
vim.o.hidden = true
